<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UseWindowsForms Condition="'$(TargetFramework)' == 'net10.0-windows'">true</UseWindowsForms>
    <AssemblyName>TaskManager.Tests</AssemblyName>
    <RootNamespace>TaskManager.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\TaskManager.App\TaskManager.App.csproj" />
  </ItemGroup>
</Project>
