<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>taskctl</AssemblyName>
    <RootNamespace>TaskManager.CliHost</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\TaskManager.App\TaskManager.App.csproj" />
  </ItemGroup>
</Project>
